
POSITION_LONG = "LONG"
POSITION_SHORT = "SHORT"

POSITION_CHECK_SL = "POSITION_CHECK_STOP_LOSS"
POSITION_CHECK_TP = "POSITION_CHECK_TAKE_PROFIT"

TREND_UP = "TREND_UP"
TREND_DOWN = "TREND_DOWN"
TREND_NONE = "TREND_NONE"

PIVOT_HIGH = "PIVOT_HIGH"
PIVOT_LOW = "PIVOT_LOW"